import {
  APP_ENVIRONMENT_KEY,
  DEFAULT_ENVIRONMENT,
} from "../../../core/environments.js";
import { INFRA_FILE, SRC_DIR, sourceExt } from "../types.js";
import type { InitAnswers } from "../types.js";
import { loggerExt } from "./helpers.js";

export function gitignore(runtime: InitAnswers["runtime"]): string {
  const lines = [
    "node_modules/",
    "dist/",
    ".aws-sam/",
    ".env",
    ".env.*",
    ".DS_Store",
    "*.log",
  ];

  if (runtime === "python") {
    lines.push(".venv/", "__pycache__/", "*.pyc");
  }

  return `${lines.join("\n")}\n`;
}

function prismaSteps(answers: InitAnswers): string {
  if (answers.database !== "prisma" || answers.runtime === "python") {
    return "";
  }

  return `
## Prisma

Point \`DATABASE_URL\` in \`.env.${DEFAULT_ENVIRONMENT}\` at your database, then:

\`\`\`bash
npm run prisma:migrate    # create and apply a migration (development)
npm run prisma:generate   # regenerate the client after editing schema.prisma
npm run prisma:studio     # browse the data
\`\`\`

Deployments apply already-created migrations instead:

\`\`\`bash
npm run prisma:deploy
\`\`\`

Those scripts read \`.env.${DEFAULT_ENVIRONMENT}\`. Run them against another
environment by naming its file:

\`\`\`bash
npx dotenv -e .env.production -- npx prisma migrate deploy
\`\`\`
`;
}

export function readme(answers: InitAnswers): string {
  const layerRuntime =
    answers.layer && answers.runtime === "typescript" ? "javascript" : answers.runtime;
  const sharedFiles = [
    `│   │   └── logger.${loggerExt(layerRuntime)}`,
    ...(answers.database !== "none" ? ["│   │   └── db." + sourceExt(answers.runtime)] : []),
  ];

  const nextSteps = ["```bash", "sam build", "sam deploy --guided", "```"];

  return `# ${answers.name}

Generated by **slskit init**.

- Runtime: ${answers.runtime}
- Framework: AWS SAM
- Database: ${answers.database}
- API Gateway: ${
    answers.apiGateway
      ? "yes (each service owns an HTTP API in its own template)"
      : "no"
  }
- Common layer: ${
    answers.layer ? "yes (src/shared attached to every function)" : "no"
  }
- Function memory: ${answers.memorySize} MB

See \`slskit.json\` for the full project graph.

## Layout

Every service owns a \`${INFRA_FILE}\` next to its handlers, so services can be
deployed one at a time. The root \`template.yaml\` pulls them all together.

\`\`\`text
${answers.name}/
├── ${SRC_DIR}/
│   ├── functions/
│   │   ├── auth/
│   │   │   ├── ${INFRA_FILE}
│   │   │   ├── login/handler.${sourceExt(answers.runtime)}
│   │   │   └── register/handler.${sourceExt(answers.runtime)}
│   │   └── product/
│   │       ├── ${INFRA_FILE}
│   │       ├── getProducts/handler.${sourceExt(answers.runtime)}
│   │       └── createProduct/handler.${sourceExt(answers.runtime)}
│   ├── services/
│   │   ├── auth/login.${sourceExt(answers.runtime)}
│   │   └── product/getProducts.${sourceExt(answers.runtime)}
│   └── shared/
${sharedFiles.join("\n")}
├── template.yaml         (root stack)
├── .env.${DEFAULT_ENVIRONMENT}              (the "${DEFAULT_ENVIRONMENT}" environment's values, gitignored)
├── package.json
├── slskit.json
└── README.md
\`\`\`

Each function delegates to a matching service module: \`${SRC_DIR}/functions/auth/login\`
calls \`${SRC_DIR}/services/auth/login\`.

## Environments

The project starts with one environment, \`${DEFAULT_ENVIRONMENT}\`, and its values live in
\`.env.${DEFAULT_ENVIRONMENT}\`. Add more as you need them -- each one gets its own file,
its own CloudFormation stack, and its own \`${APP_ENVIRONMENT_KEY}\`.

\`\`\`bash
slskit env list
slskit env add production --profile prod-admin --region eu-west-2
slskit env set LOG_LEVEL=debug
\`\`\`

## Next steps

${nextSteps.join("\n")}
${prismaSteps(answers)}`;
}

export function packageJson(answers: InitAnswers): string {
  const isNode = answers.runtime !== "python";
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};

  if (isNode) {
    if (answers.runtime === "typescript") {
      devDependencies.typescript = "^5.7.2";
      devDependencies["@types/node"] = "^22.10.2";
      devDependencies["@types/aws-lambda"] = "^8.10.145";
    }

    if (answers.database === "prisma") {
      dependencies["@prisma/client"] = "^6.5.0";
      devDependencies.prisma = "^6.5.0";
      // The Prisma CLI only reads ".env"; this points it at the environment file instead.
      devDependencies["dotenv-cli"] = "^8.0.0";
    }

    if (answers.database === "mongoose") {
      dependencies.mongoose = "^8.12.1";
    }

    if (answers.database === "dynamodb") {
      dependencies["@aws-sdk/client-dynamodb"] = "^3.750.0";
      dependencies["@aws-sdk/lib-dynamodb"] = "^3.750.0";
    }

    // sam build stages the project with `npm install --omit=dev`, so esbuild must be a regular dependency.
    dependencies.esbuild = "^0.25.0";
  }

  const scripts: Record<string, string> = {
    build: "sam build",
    deploy: "sam deploy --guided",
  };

  if (answers.runtime === "typescript") {
    scripts.typecheck = "tsc --noEmit";
  }

  if (answers.database === "prisma" && isNode) {
    const withEnv = `dotenv -e .env.${DEFAULT_ENVIRONMENT} --`;
    scripts["prisma:generate"] = `${withEnv} prisma generate`;
    scripts["prisma:migrate"] = `${withEnv} prisma migrate dev`;
    // migrate dev is interactive and dev-only; deployments need migrate deploy.
    scripts["prisma:deploy"] = `${withEnv} prisma migrate deploy`;
    scripts["prisma:studio"] = `${withEnv} prisma studio`;
  }

  return `${JSON.stringify(
    {
      name: answers.name,
      version: "0.1.0",
      private: true,
      description: `${answers.name} AWS SAM app generated by slskit`,
      scripts,
      dependencies,
      devDependencies,
    },
    null,
    2
  )}\n`;
}

export function tsconfig(answers: InitAnswers): string {
  const compilerOptions: Record<string, unknown> = {
    target: "ES2020",
    module: "node16",
    moduleResolution: "node16",
    lib: ["ES2020"],
    strict: true,
    esModuleInterop: true,
    forceConsistentCasingInFileNames: true,
    skipLibCheck: true,
    types: ["node"],
    outDir: "dist",
    rootDir: SRC_DIR,
  };

  if (answers.layer && answers.runtime !== "python") {
    compilerOptions.paths = {
      "/opt/nodejs/*": [`./${SRC_DIR}/shared/nodejs/*`],
    };
  }

  // "sam build" copies the whole project root -- tsconfig.json included -- into
  // .aws-sam/build/<Function>/, and wipes it on the next build. Without an explicit
  // exclude an editor loads those copies as extra TypeScript programs and then
  // reports their vanished files as "not found" against this include pattern.
  return `${JSON.stringify(
    {
      compilerOptions,
      include: [`${SRC_DIR}/**/*.ts`],
      exclude: ["node_modules", "dist", ".aws-sam", ".venv"],
    },
    null,
    2
  )}\n`;
}

// The connection string a database needs, seeded into the first environment file as
// an ordinary stage variable. DynamoDB is absent on purpose: the templates create
// those tables and hardcode their names, so they are not stage configuration.
export function databaseSeedVariables(
  database: InitAnswers["database"]
): string | undefined {
  if (database === "prisma") {
    return `DATABASE_URL="postgresql://user:password@localhost:5432/app"\n`;
  }
  if (database === "mongoose") {
    return `MONGODB_URI="mongodb://127.0.0.1:27017/app"\n`;
  }
  return undefined;
}

// Matches the format "slskit env set" writes, so the two never fight over the file.
export function environmentDotenv(
  environment: string,
  database: InitAnswers["database"]
): string {
  const lines = [`${APP_ENVIRONMENT_KEY}=${environment}`];

  const dbExample = databaseSeedVariables(database);
  if (dbExample) {
    lines.push(...dbExample.trimEnd().split("\n"));
  }

  return `# Values for the "${environment}" environment. Never commit this file.\n${lines.join("\n")}\n`;
}

export function requirementsTxt(answers: InitAnswers): string {
  const lines = ["boto3>=1.35.0"];
  if (answers.database === "prisma") {
    lines.push("prisma>=0.15.0");
  }
  if (answers.database === "mongoose") {
    lines.push("pymongo>=4.10.0");
  }
  return `${lines.join("\n")}\n`;
}
