import { INFRA_FILE, SRC_DIR, sourceExt } from "../types.js";
import type { InitAnswers } from "../types.js";
import { loggerExt } from "./helpers.js";

export function gitignore(runtime: InitAnswers["runtime"]): string {
  const lines = [
    "node_modules/",
    "dist/",
    ".aws-sam/",
    ".env",
    ".env.*",
    "!.env.example",
    ".DS_Store",
    "*.log",
  ];

  if (runtime === "python") {
    lines.push(".venv/", "__pycache__/", "*.pyc");
  }

  return `${lines.join("\n")}\n`;
}

function prismaSteps(answers: InitAnswers): string {
  if (answers.database !== "prisma" || answers.runtime === "python") {
    return "";
  }

  return `
## Prisma

Point \`DATABASE_URL\` in \`.env\` at your database, then:

\`\`\`bash
npm run prisma:migrate    # create and apply a migration (development)
npm run prisma:generate   # regenerate the client after editing schema.prisma
npm run prisma:studio     # browse the data
\`\`\`

Deployments apply already-created migrations instead:

\`\`\`bash
npm run prisma:deploy
\`\`\`
`;
}

export function readme(answers: InitAnswers): string {
  const layerRuntime =
    answers.layer && answers.runtime === "typescript" ? "javascript" : answers.runtime;
  const sharedFiles = [
    `│   │   └── logger.${loggerExt(layerRuntime)}`,
    ...(answers.database !== "none" ? ["│   │   └── db." + sourceExt(answers.runtime)] : []),
  ];

  const nextSteps = ["```bash", "sam build", "sam deploy --guided", "```"];

  return `# ${answers.name}

Generated by **slskit init**.

- Runtime: ${answers.runtime}
- Framework: AWS SAM
- Database: ${answers.database}
- API Gateway: ${
    answers.apiGateway
      ? "yes (each service owns an HTTP API in its own template)"
      : "no"
  }
- Common layer: ${
    answers.layer ? "yes (src/shared attached to every function)" : "no"
  }
- Function memory: ${answers.memorySize} MB

See \`sless.json\` for the full project graph.

## Layout

Every service owns a \`${INFRA_FILE}\` next to its handlers, so services can be
deployed one at a time. The root \`template.yaml\` pulls them all together.

\`\`\`text
${answers.name}/
├── ${SRC_DIR}/
│   ├── functions/
│   │   ├── auth/
│   │   │   ├── ${INFRA_FILE}
│   │   │   ├── login/handler.${sourceExt(answers.runtime)}
│   │   │   └── register/handler.${sourceExt(answers.runtime)}
│   │   └── product/
│   │       ├── ${INFRA_FILE}
│   │       ├── getProducts/handler.${sourceExt(answers.runtime)}
│   │       └── createProduct/handler.${sourceExt(answers.runtime)}
│   ├── services/
│   │   ├── auth/login.${sourceExt(answers.runtime)}
│   │   └── product/getProducts.${sourceExt(answers.runtime)}
│   └── shared/
${sharedFiles.join("\n")}
├── template.yaml         (root stack)
├── package.json
├── sless.json
└── README.md
\`\`\`

Each function delegates to a matching service module: \`${SRC_DIR}/functions/auth/login\`
calls \`${SRC_DIR}/services/auth/login\`.

## Next steps

${nextSteps.join("\n")}
${prismaSteps(answers)}`;
}

export function packageJson(answers: InitAnswers): string {
  const isNode = answers.runtime !== "python";
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};

  if (isNode) {
    if (answers.runtime === "typescript") {
      devDependencies.typescript = "^5.7.2";
      devDependencies["@types/node"] = "^22.10.2";
      devDependencies["@types/aws-lambda"] = "^8.10.145";
    }

    if (answers.database === "prisma") {
      dependencies["@prisma/client"] = "^6.5.0";
      devDependencies.prisma = "^6.5.0";
    }

    if (answers.database === "mongoose") {
      dependencies.mongoose = "^8.12.1";
    }

    if (answers.database === "dynamodb") {
      dependencies["@aws-sdk/client-dynamodb"] = "^3.750.0";
      dependencies["@aws-sdk/lib-dynamodb"] = "^3.750.0";
    }

    // sam build stages the project with `npm install --omit=dev`, so esbuild must be a regular dependency.
    dependencies.esbuild = "^0.25.0";
  }

  const scripts: Record<string, string> = {
    build: "sam build",
    deploy: "sam deploy --guided",
  };

  if (answers.database === "prisma" && isNode) {
    scripts["prisma:generate"] = "prisma generate";
    scripts["prisma:migrate"] = "prisma migrate dev";
    // migrate dev is interactive and dev-only; deployments need migrate deploy.
    scripts["prisma:deploy"] = "prisma migrate deploy";
    scripts["prisma:studio"] = "prisma studio";
  }

  return `${JSON.stringify(
    {
      name: answers.name,
      version: "0.1.0",
      private: true,
      description: `${answers.name} AWS SAM app generated by slskit`,
      scripts,
      dependencies,
      devDependencies,
    },
    null,
    2
  )}\n`;
}

export function tsconfig(answers: InitAnswers): string {
  const compilerOptions: Record<string, unknown> = {
    target: "ES2020",
    module: "node16",
    moduleResolution: "node16",
    lib: ["ES2020"],
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    types: ["node"],
    outDir: "dist",
    rootDir: SRC_DIR,
  };

  if (answers.layer && answers.runtime !== "python") {
    compilerOptions.paths = {
      "/opt/nodejs/*": [`./${SRC_DIR}/shared/nodejs/*`],
    };
  }

  return `${JSON.stringify(
    {
      compilerOptions,
      include: [`${SRC_DIR}/**/*.ts`],
    },
    null,
    2
  )}\n`;
}

export function envExample(database: InitAnswers["database"]): string | undefined {
  if (database === "prisma") {
    return `DATABASE_URL="postgresql://user:password@localhost:5432/app"\n`;
  }
  if (database === "mongoose") {
    return `MONGODB_URI="mongodb://127.0.0.1:27017/app"\n`;
  }
  if (database === "dynamodb") {
    return `USERS_TABLE="users"\nPRODUCTS_TABLE="products"\n`;
  }
  return undefined;
}

export function requirementsTxt(answers: InitAnswers): string {
  const lines = ["boto3>=1.35.0"];
  if (answers.database === "prisma") {
    lines.push("prisma>=0.15.0");
  }
  if (answers.database === "mongoose") {
    lines.push("pymongo>=4.10.0");
  }
  return `${lines.join("\n")}\n`;
}
